### ISSUE TITLE
binding processing handles folders incorrectly

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#41]
The binding processing (splitting by chroms and building segtrees) is not handling folders correctly. 
Below I'm uploading the same bw file three times, but with different data names, targeting respectively at 
- a non-existing chr folder;
- an existing but empty chr folder
- an existing but non-empty chr folder

If the target folder does NOT exist, it fails to create a folder:

```
POST upload
start transfer
/home/bowen/vbox/bigWigToWig /home/bowen/vbox/genotet_data/wiggle/not_exist /home/bowen/vbox/genotet_data/wiggle/not_exist.wig
fs.js:844
  return binding.lstat(pathModule._makeLong(path));
                                  ^

Error: ENOENT: no such file or directory, lstat '/home/bowen/vbox/genotet_data/wiggle/not_exist_chr'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at Interface.<anonymous> (/var/www/html/genotet/server/uploader.js:116:22)
    at emitNone (events.js:72:20)
    at Interface.emit (events.js:166:7)
    at Interface.close (readline.js:285:8)
    at ReadStream.onend (readline.js:94:10)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
```

If the folder EXISTS but is EMPTY, it is working properly:

```
POST upload
start transfer
/home/bowen/vbox/bigWigToWig /home/bowen/vbox/genotet_data/wiggle/empty /home/bowen/vbox/genotet_data/wiggle/empty.wig
Wiggle file empty is replaced.
```

If the folder EXISTS but is NOT EMPTY, it is NOT working correctly:

```
Error: ENOTEMPTY: directory not empty, rmdir '/home/bowen/vbox/genotet_data/wiggle/not_empty_chr'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:763:18)
    at Interface.<anonymous> (/var/www/html/genotet/server/uploader.js:118:12)
    at emitNone (events.js:72:20)
    at Interface.emit (events.js:166:7)
    at Interface.close (readline.js:285:8)
    at ReadStream.onend (readline.js:94:10)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
```

**Comment by yubowenok** [comment]
bed upload seems to have a similar problem. The server aborts abnormally if the bed folder already exists.

**Comment by djasmine** [comment]
I don't know what will happen in server, it could pass the upload test in my computer and travis server. Maybe we are going to test it on the Simons server.

**Comment by yubowenok** [comment]
Upload tests do not cover existing folder. You need to make sure that you handled user uploading the same fileName twice.

**Comment by yubowenok** [comment]
Was this fixed? @djasmine

**Comment by djasmine** [comment]
fixed
